'use client';
import {useEffect,useState} from 'react';
import {useAccount,useWalletClient} from 'wagmi';
import {ensureWalletSession} from '../../lib/walletSession';
type Tag={label:string;author:string;private:boolean};
export default function ArtworkTags({chainId,contract,tokenId}:{chainId:number;contract:string;tokenId:string}){
 const {address}=useAccount();const {data:wallet}=useWalletClient();const [tags,setTags]=useState<Tag[]>([]);const [publicTags,setPublic]=useState('');const [privateTags,setPrivate]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [attempt,setAttempt]=useState(0);const [query,setQuery]=useState('');
 const path=`/api/indexer/api/artwork/${contract}/${tokenId}/tags?_chainId=${chainId}`;
 useEffect(()=>{let active=true;setTags([]);setPublic('');setPrivate('');void fetch(path,{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error('Tags are temporarily unavailable.');const payload=await response.json();if(active){setTags(payload.tags);setPublic(payload.tags.filter((t:Tag)=>!t.private&&t.author===address?.toLowerCase()).map((t:Tag)=>t.label).join(', '));setPrivate(payload.tags.filter((t:Tag)=>t.private&&t.author===address?.toLowerCase()).map((t:Tag)=>t.label).join(', '));}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[path,address,attempt]);
 async function save(){if(!address||!wallet)return;setBusy(true);setMessage('');try{await ensureWalletSession(address,args=>wallet.signMessage(args),chainId);const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicTags:publicTags.split(',').map(t=>t.trim()).filter(Boolean),privateTags:privateTags.split(',').map(t=>t.trim()).filter(Boolean)})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Tags could not be saved.');setMessage('Tags saved. Original NFT metadata is unchanged.');setAttempt(v=>v+1);}catch(error){setMessage(error instanceof Error?error.message:'Tags could not be saved.');}finally{setBusy(false);}}
 return <section className="card formCard"><h2>Artwork tags</h2><p className="hint">Offchain annotations attributed to the wallet that added them. These do not change the original NFT traits.</p>{tags.length>0&&<><label>Filter tags<input value={query} onChange={e=>setQuery(e.target.value)}/></label><ul>{tags.filter(t=>(!t.private||t.author===address?.toLowerCase())&&t.label.includes(query.toLowerCase())).map(t=><li key={`${t.author}:${t.label}`}>{t.label} · {t.private?'Private':`${t.author.slice(0,6)}…${t.author.slice(-4)}`}</li>)}</ul></>}{address&&<details><summary>Organize your artwork</summary><p>Current owners can save up to 20 tags. Public annotations remain attributed to their author after a transfer.</p><label>Public tags<input value={publicTags} maxLength={660} onChange={e=>setPublic(e.target.value)}/></label><label>Private tags<input value={privateTags} maxLength={660} onChange={e=>setPrivate(e.target.value)}/></label><p className="hint">Separate tags with commas. Private tags are visible only to your signed-in wallet.</p><button disabled={busy||!wallet} onClick={()=>void save()}>{busy?'Saving…':'Save tags'}</button></details>}<p role="status">{message}</p></section>;
}
