'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAccount} from 'wagmi';
import {fetchCollectionTokens,type ApiCollectionTokens,type ApiMintFeedItem} from '../../lib/indexerApi';
import {getAppChain} from '../../lib/chains';
import {collectionPath} from '../../lib/assetRoutes';
import ArtworkCard from './ArtworkCard';
import ArtworkTags from './ArtworkTags';
import {useNftMetadataPreview} from '../../lib/nftMetadata';
import ArtworkImage from '../profile/ArtworkImage';
export default function AssetDetailClient({chainId,address,tokenId,initialData}:{chainId:number;address:string;tokenId?:string;initialData?:ApiCollectionTokens|null}) {
  const {address:viewer}=useAccount();
  const [cursor,setCursor]=useState<string|undefined>();const [nextCursor,setNextCursor]=useState<string|null>(null);
  useEffect(()=>{setCursor(undefined);setItems(initialData?.tokens||[]);},[address,chainId,tokenId,initialData]);
  const [items,setItems]=useState<ApiMintFeedItem[]>(initialData?.tokens||[]); const [loading,setLoading]=useState(!initialData); const [error,setError]=useState(''); const [attempt,setAttempt]=useState(0);
  useEffect(()=>{let active=true;setLoading(!initialData||!!cursor);setError('');if(!cursor)setItems(initialData?.tokens||[]);void fetchCollectionTokens(address,{chainId,readOnly:true,tokenId,cursor}).then(data=>{if(active){setItems(current=>cursor?[...current,...data.tokens]:data.tokens);setNextCursor(data.nextCursor||null);}}).catch(()=>{if(active)setError('Artwork is temporarily unavailable. Please retry.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[address,chainId,attempt,tokenId,cursor,initialData]);
  const item=items.find(item=>item.tokenId===tokenId); const collection=items[0]?.collection;
  const metadata=useNftMetadataPreview({metadataUri:item?.metadataUrl||item?.metadataCid,mediaUri:item?.mediaUrl,gateway:(process.env.NEXT_PUBLIC_IPFS_GATEWAY||'https://ipfs.io')+'/ipfs'});
  return <section className="studioPage"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/discover">Explore</Link><span>/</span>{tokenId ? <Link href={collectionPath(chainId,address)}>Collection</Link>:<span>Collection</span>}{tokenId && <><span>/</span><span>#{tokenId}</span></>}</nav><header className="pageHeading"><p className="eyebrow">{getAppChain(chainId).name} · {tokenId ? 'NFT' : 'Collection'}</p><h1>{tokenId ? item?.draftName || metadata.name || `Artwork #${tokenId}` : collection?.ensSubname || 'Collection'}</h1><details><summary>Contract details</summary><p className="receiptHash">{address}</p><p>{collection?.standard}</p></details>{viewer&&collection?.ownerAddress.toLowerCase()===viewer.toLowerCase() && <Link href={`/mint?view=manage&address=${address}&chainId=${chainId}`}>Manage collection</Link>}</header>{error ? <div role="alert"><p>{error}</p><button onClick={()=>setAttempt(v=>v+1)}>Retry</button></div>:loading ? <p role="status">Loading artwork…</p>:tokenId ? item ? <div className="createLayout"><div className="artworkDetailImage"><ArtworkImage source={item.mediaUrl || metadata.imageUrl || (item.mediaCid ? `ipfs://${item.mediaCid}`:'')} alt={item.draftName || `Artwork #${tokenId}`}/></div><div className="card formCard"><h2>About this artwork</h2><p>{item.draftDescription || metadata.description || 'No description provided.'}</p><dl><dt>Creator</dt><dd>{/^0x0{40}$/.test(item.creatorAddress)?"Not verified for this imported artwork":<Link className="receiptHash" href={`/profile/${item.creatorAddress}`}>{item.creatorAddress}</Link>}</dd><dt>Indexed owner</dt><dd><Link className="receiptHash" href={`/profile/${item.ownerAddress}`}>{item.ownerAddress}</Link></dd><dt>Token ID</dt><dd>{tokenId}</dd></dl><p>{item.activeListing ? 'This artwork has an indexed listing.' : 'This artwork is not listed for sale.'}</p>{item.activeListing&&<Link className="ctaLink" href="/marketplace">View marketplace</Link>}</div></div>:<p role="status">This NFT has not been indexed yet.</p>:items.length ? <div className="creatorArtworkGrid">{items.map(item=><ArtworkCard item={item} key={item.id}/>)}</div>:<p role="status">No indexed artwork is available in this collection yet.</p>}{!tokenId&&nextCursor&&<button disabled={loading} onClick={()=>setCursor(nextCursor)}>Load more artwork</button>}{tokenId&&item&&<ArtworkTags chainId={chainId} contract={address} tokenId={tokenId}/>}</section>;
}
