'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useAccount,useWalletClient} from 'wagmi';
import {getEnabledAppChains,getPrimaryAppChainId} from '../../lib/chains';
import {ensureWalletSession} from '../../lib/walletSession';
import {nftPath,validAssetRoute} from '../../lib/assetRoutes';
export default function ImportArtworkClient(){
 const {address}=useAccount();const {data:wallet}=useWalletClient();const [chainId,setChainId]=useState(getPrimaryAppChainId);const [contract,setContract]=useState('');const [ids,setIds]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [results,setResults]=useState<Array<{tokenId:string;ok:boolean;error?:string}>>([]);
 async function importTokens(){if(!address||!wallet||busy)return;const tokens=[...new Set(ids.split(/[\s,]+/).filter(Boolean))];if(!tokens.length||tokens.length>10||tokens.some(id=>!validAssetRoute(String(chainId),contract,id))){setMessage('Enter a valid collection contract and 1–10 token IDs.');return;}
 setBusy(true);setResults([]);setMessage('Confirm sign-in to add artwork to your profile.');try{await ensureWalletSession(address,args=>wallet.signMessage(args),chainId);for(const tokenId of tokens){setMessage(`Checking ownership and importing #${tokenId}…`);const response=await fetch(`/api/indexer/api/imports?_chainId=${chainId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractAddress:contract,tokenIds:[tokenId]}),signal:AbortSignal.timeout(65000)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Import unavailable.');setResults(current=>[...current,...payload.results]);}setMessage('Import checks completed. Review the results below.');}catch(error){setMessage(error instanceof Error?error.message:'Import interrupted. Completed items are saved; you can retry the remaining IDs.');}finally{setBusy(false);}}
 return <section className="studioPage"><header className="pageHeading"><Link href="/profile">My studio</Link><h1>Bring your collection with you.</h1><p>Add existing NFTs to your profile. Your wallet must currently own the tokens. Importing does not mint, transfer, or approve spending.</p></header><div className="card formCard"><label>Network<select disabled={busy} value={chainId} onChange={e=>{setChainId(Number(e.target.value));setResults([]);}}>{getEnabledAppChains().map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Collection contract<input disabled={busy} value={contract} onChange={e=>{setContract(e.target.value.trim());setResults([]);}} placeholder="0x…" maxLength={42}/></label><label>Token IDs<textarea disabled={busy} value={ids} onChange={e=>{setIds(e.target.value);setResults([]);}} placeholder="1, 2, 3" maxLength={800}/></label><p className="hint">ERC-721 and ERC-1155 supported. Import up to 10 IDs at a time. Importing establishes ownership, not authorship or collection administration.</p><button disabled={!address||!wallet||busy} onClick={()=>void importTokens()}>{busy?'Importing…':'Verify ownership & import'}</button>{!address&&<p>Connect your wallet using the button at the top to continue.</p>}<p role="status">{message}</p><ul>{results.map(result=><li key={result.tokenId}>{result.ok?<Link href={nftPath(chainId,contract,result.tokenId)}>View imported NFT #{result.tokenId}</Link>:`#${result.tokenId}: ${result.error}`}</li>)}</ul>{results.some(result=>result.ok)&&<Link href={`/profile/${address?.toLowerCase()}`}>View your profile</Link>}</div></section>;
}
