'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useAccount,useWalletClient} from 'wagmi';
import {IMPORT_NETWORKS} from '../../../../packages/profile/import-networks.mjs';
import {ensureWalletSession} from '../../lib/walletSession';
import {useNftMetadataPreview} from '../../lib/nftMetadata';
import ArtworkImage from '../profile/ArtworkImage';
import {nftPath,validAssetRoute} from '../../lib/assetRoutes';
import {emptyImportDraft,importDraftKey,readImportDraft,writeImportDraft,type ImportDraft} from '../../lib/importDraft';
type ImportResult={tokenId:string;ok:boolean;error?:string;metadataUri?:string;standard?:string;quantityRaw?:string};
function ImportPreview({item}:{item:ImportResult}){const metadata=useNftMetadataPreview({metadataUri:item.metadataUri,mediaUri:null,gateway:(process.env.NEXT_PUBLIC_IPFS_GATEWAY||'https://ipfs.io')+'/ipfs'});return <article className="card artworkCard"><ArtworkImage source={metadata.imageUrl||''} alt={metadata.name||`Artwork #${item.tokenId}`}/><div className="artworkCardBody"><h3>{metadata.name||`Artwork #${item.tokenId}`}</h3><p>{item.standard} · Owned quantity: {item.quantityRaw}</p><p>{metadata.description}</p></div></article>;}
export default function ImportArtworkClient(){
 const {address,status}=useAccount();const {data:wallet}=useWalletClient();const [chainId,setChainId]=useState(1);const [contract,setContract]=useState('');const [ids,setIds]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [results,setResults]=useState<ImportResult[]>([]);
 const draftKey=importDraftKey(address);const loadedKey=useRef<string|null>(null);const previousKey=useRef<string|null>(null);const [draftReady,setDraftReady]=useState(false);const [draftNotice,setDraftNotice]=useState('');
 useEffect(()=>{
  setDraftReady(false);loadedKey.current=null;
  if(status==='reconnecting'||status==='connecting')return;
  let draft=emptyImportDraft();
  try{let saved=readImportDraft(draftKey);if(!saved&&address&&previousKey.current===importDraftKey()){saved=readImportDraft(importDraftKey());if(saved){writeImportDraft(draftKey,saved);localStorage.removeItem(importDraftKey());}}if(saved){draft=saved;setDraftNotice('Draft restored on this browser. Preview again to verify ownership.');}else setDraftNotice('Your entries are saved automatically on this browser.');}catch{setDraftNotice('Browser storage is unavailable. Keep this page open to retain your entries.');}
  setChainId(draft.chainId);setContract(draft.contract);setIds(draft.ids);loadedKey.current=draftKey;previousKey.current=draftKey;setDraftReady(true);
 },[draftKey,status,address]);
 function changeDraft(change:Partial<ImportDraft>){
  if(loadedKey.current!==draftKey)return;
  const next={chainId,contract,ids,...change};setChainId(next.chainId);setContract(next.contract);setIds(next.ids);
  try{writeImportDraft(draftKey,next);setDraftNotice('Draft saved on this browser.');}catch{setDraftNotice('Browser storage is unavailable. Keep this page open to retain your entries.');}
 }
 function clearDraft(){if(loadedKey.current!==draftKey)return;const draft=emptyImportDraft();setChainId(draft.chainId);setContract('');setIds('');setReviewed(false);setResults([]);try{localStorage.removeItem(draftKey);setDraftNotice('Draft cleared.');}catch{setDraftNotice('Could not clear browser storage.');}}
 const [reviewed,setReviewed]=useState(false);const generation=useRef(0);
 useEffect(()=>{generation.current++;setReviewed(false);setResults([]);setMessage('');},[address,chainId,contract,ids]);
 async function importTokens(previewOnly:boolean){if(!address||!wallet||busy||!draftReady||loadedKey.current!==draftKey)return;const tokens=[...new Set(ids.split(/[\s,]+/).filter(Boolean))];if(!tokens.length||tokens.length>10||tokens.some(id=>!validAssetRoute(String(chainId),contract,id))){setMessage('Enter a valid collection contract and 1–10 token IDs.');return;}
 const gen=generation.current;if(!previewOnly)setReviewed(false);setBusy(true);setResults([]);setMessage('Confirm sign-in to add artwork to your profile.');try{await ensureWalletSession(address,args=>wallet.signMessage(args));for(const tokenId of tokens){if(generation.current!==gen)return;setMessage(`${previewOnly?'Checking':'Importing'} #${tokenId}…`);const response=await fetch(`/api/indexer/api/imports?_chainId=${chainId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractAddress:contract,tokenIds:[tokenId],preview:previewOnly}),signal:AbortSignal.timeout(65000)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Import unavailable.');if(generation.current!==gen)return;setResults(current=>[...current,...payload.results]);}setReviewed(previewOnly);setMessage(previewOnly?'Review your artwork below. Nothing has been added yet.':'Import completed. Review any items that need a retry.');}catch(error){setMessage(error instanceof Error?error.message:'Import interrupted. Completed items are saved; you can retry the remaining IDs.');}finally{setBusy(false);}}
 return <section className="studioPage"><header className="pageHeading"><Link href="/profile">My studio</Link><h1>Bring your collection with you.</h1><p>Add existing NFTs to your profile. Your wallet must currently own the tokens. Importing does not mint, transfer, or approve spending.</p></header><div className="card formCard"><label>Network<select disabled={busy||!draftReady} value={chainId} onChange={e=>{changeDraft({chainId:Number(e.target.value)});setResults([]);}}>{IMPORT_NETWORKS.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="hint">Choose the network where your NFT lives. You do not need to switch your wallet network to import.</p><label>Collection contract<input disabled={busy||!draftReady} value={contract} onChange={e=>{changeDraft({contract:e.target.value.trim()});setResults([]);}} placeholder="0x…" maxLength={42}/></label><label>Token IDs<textarea disabled={busy||!draftReady} value={ids} onChange={e=>{changeDraft({ids:e.target.value});setResults([]);}} placeholder="1, 2, 3" maxLength={800}/></label><div className="row"><p className="hint" role="status">{draftNotice}</p><button type="button" className="secondary" disabled={busy||!draftReady} onClick={clearDraft}>Clear import draft</button></div><p className="hint">ERC-721 and ERC-1155 supported. Import up to 10 IDs at a time. Importing establishes ownership, not authorship or collection administration.</p><button disabled={!address||!wallet||busy||!draftReady} onClick={()=>void importTokens(true)}>{busy?'Checking…':'Preview artwork'}</button>{reviewed&&results.some(result=>result.ok)&&<button disabled={busy} onClick={()=>void importTokens(false)}>Import verified artwork</button>}{!address&&<p>Connect your wallet using the button at the top to continue.</p>}<p role="status">{message}</p><ul>{results.map(result=><li key={result.tokenId}>{result.ok&&reviewed?<ImportPreview item={result}/>:result.ok?<Link href={nftPath(chainId,contract,result.tokenId)}>View imported NFT #{result.tokenId}</Link>:`#${result.tokenId}: ${result.error}`}</li>)}</ul>{!reviewed&&results.some(result=>result.ok)&&<Link href={`/profile/${address?.toLowerCase()}`}>View your profile</Link>}</div></section>;
}
