'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useAccount,useWalletClient} from 'wagmi';
import {getEnabledAppChains,getPrimaryAppChainId} from '../../lib/chains';
import {ensureWalletSession} from '../../lib/walletSession';
import {nftPath,validAssetRoute} from '../../lib/assetRoutes';
type Match={id:string;label:string;private:boolean;tokenId:string;contractAddress:string;chainId:number;name?:string};
export default function TagWorkspaceClient(){
 const {address}=useAccount();const {data:wallet}=useWalletClient();
 const [chainId,setChainId]=useState(getPrimaryAppChainId),[query,setQuery]=useState(''),[matches,setMatches]=useState<Match[]>([]),[cursor,setCursor]=useState<string|null>(null);
 const [contract,setContract]=useState(''),[ids,setIds]=useState(''),[labels,setLabels]=useState(''),[visibility,setVisibility]=useState('private'),[mode,setMode]=useState('add');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<string[]>([]);const generation=useRef(0);
 useEffect(()=>{generation.current++;setMatches([]);setCursor(null);setResults([]);setMessage('');},[address,chainId]);
 async function search(more=false){if(!address||!wallet||busy)return;const gen=generation.current;setBusy(true);setMessage('');try{await ensureWalletSession(address,args=>wallet.signMessage(args),chainId);if(gen!==generation.current)return;const response=await fetch(`/api/indexer/api/artwork/tags/search?_chainId=${chainId}&q=${encodeURIComponent(query)}${more&&cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search unavailable.');if(gen!==generation.current)return;setMatches(previous=>more?[...previous,...data.items]:data.items);setCursor(data.nextCursor);if(!data.items.length)setMessage('No matching tags found for your signed-in wallet.');}catch(error){if(gen===generation.current)setMessage(error instanceof Error?error.message:'Search unavailable.');}finally{setBusy(false);}}
 async function edit(){if(!address||!wallet||busy)return;const tokens=[...new Set(ids.split(/[\s,]+/).filter(Boolean))],tags=[...new Set(labels.split(',').map(tag=>tag.trim()).filter(Boolean))];if(!tokens.length||tokens.length>10||tokens.some(id=>!validAssetRoute(String(chainId),contract,id))||!tags.length||tags.length>20){setMessage('Choose a valid contract, 1–10 token IDs, and 1–20 comma-separated tags.');return;}const gen=generation.current;setBusy(true);setResults([]);setMessage('Confirm sign-in to organize this artwork.');try{await ensureWalletSession(address,args=>wallet.signMessage(args),chainId);for(const tokenId of tokens){if(gen!==generation.current)return;const response=await fetch(`/api/indexer/api/artwork/${contract}/${tokenId}/tags?_chainId=${chainId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,publicTags:visibility==='public'?tags:[],privateTags:visibility==='private'?tags:[]})});const data=await response.json();if(gen!==generation.current)return;setResults(previous=>[...previous,`#${tokenId}: ${response.ok?'Tags updated':data.error||'Could not update'}`]);}setMessage('Finished. Any unsuccessful items can be retried.');}catch(error){if(gen===generation.current)setMessage(error instanceof Error?error.message:'Update interrupted; completed items are saved.');}finally{setBusy(false);}}
 return <section className="studioPage"><header className="pageHeading"><Link href="/profile">My studio</Link><h1>Organize your artwork.</h1><p>Search your tags and update several NFTs at once. Original NFT metadata stays unchanged.</p></header><label>Network<select disabled={busy} value={chainId} onChange={e=>setChainId(Number(e.target.value))}>{getEnabledAppChains().map(chain=><option key={chain.id} value={chain.id}>{chain.name}</option>)}</select></label>{!address&&<p>Connect your wallet to search and edit your annotations.</p>}<section className="card formCard"><h2>Find tagged artwork</h2><label>Search your tags<input maxLength={32} disabled={busy} value={query} onChange={e=>{setQuery(e.target.value);setMatches([]);setCursor(null);}}/></label><button disabled={busy||!address||!query.trim()} onClick={()=>void search()}>Search my tags</button><ul>{matches.map(item=><li key={item.id}><Link href={nftPath(item.chainId,item.contractAddress,item.tokenId)}>{item.name||`Artwork #${item.tokenId}`}</Link> · {item.label} · {item.private?'Private':'Public'}</li>)}</ul>{cursor&&<button disabled={busy} onClick={()=>void search(true)}>Load more matches</button>}</section><section className="card formCard"><h2>Update several NFTs</h2><p className="hint">Current ownership is checked for every item. Only your annotations change; other authors’ tags are preserved.</p><label>Collection contract<input disabled={busy} value={contract} maxLength={42} onChange={e=>setContract(e.target.value.trim())}/></label><label>Token IDs<textarea disabled={busy} value={ids} maxLength={800} onChange={e=>setIds(e.target.value)}/></label><label>Tags, separated by commas<input disabled={busy} value={labels} maxLength={660} onChange={e=>setLabels(e.target.value)}/></label><label>Visibility<select disabled={busy} value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Private — only your signed-in wallet</option><option value="public">Public — visible to everyone</option></select></label><label>Action<select disabled={busy} value={mode} onChange={e=>setMode(e.target.value)}><option value="add">Add tags</option><option value="remove">Remove tags</option></select></label><p>Adding a tag sets its selected visibility. Up to 20 tags are allowed per NFT.</p><button disabled={busy||!address||!wallet} onClick={()=>void edit()}>{busy?'Working…':`${mode==='add'?'Add':'Remove'} ${visibility} tags`}</button><ul>{results.map(result=><li key={result}>{result}</li>)}</ul></section><p role="status">{message}</p></section>;
}
