import {it,expect,vi} from 'vitest';
import {verifyCollectionAuthority,discoverCollectionArtwork} from './collectionImport.js';
import {importArtwork} from './artwork.js';
const wallet='0x1111111111111111111111111111111111111111',other='0x2222222222222222222222222222222222222222',contract='0x3333333333333333333333333333333333333333';
function reader(owner=wallet){return {getChainId:vi.fn().mockResolvedValue(1),readContract:vi.fn(async({functionName}:any)=>functionName==='owner'?owner:functionName==='hasRole'?false:functionName==='supportsInterface'?true:functionName==='ownerOf'?other:'ipfs://bafytest')};}
it('does not accept a former deployer or minter without current administrative authority',async()=>{await expect(verifyCollectionAuthority(reader(other) as any,1,contract,wallet)).rejects.toThrow('current contract owner');});
it('enumerates every contract token, regardless of holder',async()=>{const result=await discoverCollectionArtwork(reader() as any,1,wallet,contract,null,vi.fn().mockResolvedValue(Response.json({items:[{id:'1'},{id:'2'},{id:'1'}],next_page_params:{unique_token:2}})));expect(result.tokenIds).toEqual(['1','2']);expect(result.nextCursor).toEqual({unique_token:2});});
it('preserves the actual NFT owner and leaves authorship unknown during collection import',async()=>{const prisma={collection:{upsert:vi.fn().mockResolvedValue({id:'c'})},token:{upsert:vi.fn().mockResolvedValue({id:'t'})},tokenHolding:{upsert:vi.fn(),updateMany:vi.fn()}};const result=await importArtwork(prisma as any,reader() as any,1,wallet,{mode:'collection',contractAddress:contract,tokenIds:['1']});expect(result.results[0].ok).toBe(true);expect(prisma.token.upsert.mock.calls[0][0].create).toMatchObject({ownerAddress:other,creatorAddress:'0x0000000000000000000000000000000000000000'});expect(prisma.tokenHolding.upsert.mock.calls[0][0].create.ownerAddress).toBe(other);});
it('rejects revoked authority between preview and save before database writes',async()=>{const prisma={collection:{upsert:vi.fn()},token:{upsert:vi.fn()}};const client=reader();await importArtwork(prisma as any,client as any,1,wallet,{mode:'collection',contractAddress:contract,tokenIds:['1'],preview:true});client.readContract.mockImplementation(async({functionName}:any)=>functionName==='owner'?other:false);const result=await importArtwork(prisma as any,client as any,1,wallet,{mode:'collection',contractAddress:contract,tokenIds:['1']});expect(result.results[0].ok).toBe(false);expect(prisma.collection.upsert).not.toHaveBeenCalled();});
it('does not expand collected-work permissions',async()=>{const result=await importArtwork({} as any,reader() as any,1,wallet,{contractAddress:contract,tokenIds:['1']});expect(result.results[0].ok).toBe(false);});
