import {normalizeDesign,safeProfileLink,safeProfileTarget} from '../../../packages/profile/design.mjs';
import {customProfileDocument} from './profileCustomCode';
import type {ApiMintFeedItem} from './indexerApi';
const escape=(value:unknown)=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function media(value:string){if(value.startsWith('ipfs://'))return `${(process.env.NEXT_PUBLIC_IPFS_GATEWAY||'https://ipfs.nftfactory.org').replace(/\/$/,'').replace(/\/ipfs$/,'')}/ipfs/${value.slice(7)}`;return /^https:\/\//i.test(value)?value:'';}
export const pageStarterHtml='<main class="creator-page">{{intro}}<div class="profile-layout"><section class="main-column">{{featured}}{{artwork}}{{about}}</section><aside class="side-column">{{links}}{{collections}}{{top8}}{{panels}}</aside></div></main>';
export const pageStarterCss='body { background: #f1f3ef; color: #243329; }\n.creator-page { max-width: 1400px; margin: auto; }\n.profile-header { background: #e7eedf; border-radius: 20px; padding: 32px; }\nh1 { font-size: clamp(36px, 6vw, 76px); letter-spacing: -.05em; }\n.profile-layout { display: grid; grid-template-columns: 2fr 1fr; gap: 28px; }\n.profile-section { padding: 24px 0; }\na { color: #ad3515; }\n@media(max-width: 700px) { .profile-layout { grid-template-columns: 1fr; } }';
export function profilePageDocument(address:string,profile:{displayName?:string|null;bio?:string|null;aboutMe?:string|null;avatarUrl?:string|null;bannerUrl?:string|null;links?:string[];design?:unknown}|null|undefined,items:ApiMintFeedItem[]){
 const d=normalizeDesign(profile?.design);const image=(url:string,alt:string,cls='')=>media(url)?`<img class="${cls}" src="${escape(media(url))}" alt="${escape(alt)}" loading="lazy">`:'';
 const section=(title:string,body:string)=>body?`<section class="profile-section"><h2>${title}</h2>${body}</section>`:'';
 const cards=(values:ApiMintFeedItem[])=>`<div class="artwork-grid">${values.slice(0,48).map(item=>`<article class="artwork-card"><a href="https://nftfactory.org/nfts/${item.collection.chainId}/${item.collection.contractAddress}/${item.tokenId}">${image(item.mediaUrl||(item.mediaCid?`ipfs://${item.mediaCid}`:''),item.draftName||'Artwork')}<h3>${escape(item.draftName||`Artwork #${item.tokenId}`)}</h3></a></article>`).join('')}</div>`;
 const featured=d.featured.flatMap(key=>items.filter(item=>`${item.collection.chainId}:${item.collection.contractAddress.toLowerCase()}:${item.tokenId}`===key));
 const collections=[...new Map(items.map(item=>[`${item.collection.chainId}:${item.collection.contractAddress}`,item.collection])).values()];
 const slots:Record<string,string>={intro:`<header class="profile-header">${image(profile?.bannerUrl||'','Banner','profile-banner')}${image(profile?.avatarUrl||'','Avatar','profile-avatar')}<p>${escape(d.headline)}</p><h1>${escape(profile?.displayName||'Your creator name')}</h1><p>${escape(profile?.bio)}</p><small class="wallet-address">${escape(address)}</small></header>`,about:section('About',`<p>${escape(profile?.aboutMe)}</p>`),featured:featured.length?section('Featured artwork',cards(featured)):'',artwork:section('Artwork',items.length?cards(items):'<p>No artwork loaded yet.</p>'),links:section('Elsewhere',(profile?.links||[]).filter(safeProfileLink).map(link=>`<p><a href="${escape(safeProfileLink(link))}">${escape(new URL(link).hostname)}</a></p>`).join('')),collections:section('Collections',collections.map(c=>`<p><a href="https://nftfactory.org/collections/${c.chainId}/${c.contractAddress}">${escape(c.ensSubname||c.contractAddress)}</a></p>`).join('')),top8:section('Top 8',d.top8Targets.map(v=>`<p><a href="https://nftfactory.org${escape(safeProfileTarget(v.url))}">${escape(v.label)}</a></p>`).join('')||d.top8.map(v=>`<p>${escape(v)}</p>`).join('')),panels:d.panels.map(v=>section(escape(v.title),`<p>${escape(v.body)}</p>`)).join('')};
 const html=(d.customHtml||pageStarterHtml).replace(/\{\{(intro|about|featured|artwork|links|collections|top8|panels)\}\}/g,(_,key:string)=>slots[key]);
 return customProfileDocument(html,`body{background:#f1f3ef;color:#243329}img{max-width:100%}.profile-banner{width:100%;max-height:360px;object-fit:cover}.profile-avatar{width:100px;height:100px;object-fit:cover;border-radius:50%}.artwork-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:18px}.artwork-card img{width:100%;aspect-ratio:1;object-fit:cover}.wallet-address{overflow-wrap:anywhere}${d.customCss||pageStarterCss}`,true);
}
