export const CHAIN_SCOPED_PUBLIC_ENV_NAMES = [
  "NEXT_PUBLIC_RPC_URL",
  "NEXT_PUBLIC_INDEXER_API_URL",
  "NEXT_PUBLIC_REGISTRY_ADDRESS",
  "NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS",
  "NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS",
  "NEXT_PUBLIC_MARKETPLACE_ADDRESS",
  "NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS",
  "NEXT_PUBLIC_SHARED_721_ADDRESS",
  "NEXT_PUBLIC_SHARED_1155_ADDRESS",
  "NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS",
  "NEXT_PUBLIC_FACTORY_ADDRESS"
] as const;

export type ChainScopedPublicEnvName = (typeof CHAIN_SCOPED_PUBLIC_ENV_NAMES)[number];

export const ROOT_PUBLIC_ENV_NAMES = [
  "NEXT_PUBLIC_PRIMARY_CHAIN_ID",
  "NEXT_PUBLIC_CHAIN_ID",
  "NEXT_PUBLIC_ENABLED_CHAIN_IDS",
  "NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID"
] as const;

export type RootPublicEnvName = (typeof ROOT_PUBLIC_ENV_NAMES)[number];

type ChainScopedPublicEnvValues = Partial<Record<ChainScopedPublicEnvName, string | undefined>>;

function normalizeEnvValue(value: string | undefined): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

function getRootPublicEnvMap(): Record<RootPublicEnvName, string | undefined> {
  return {
    NEXT_PUBLIC_PRIMARY_CHAIN_ID: process.env.NEXT_PUBLIC_PRIMARY_CHAIN_ID,
    NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
    NEXT_PUBLIC_ENABLED_CHAIN_IDS: process.env.NEXT_PUBLIC_ENABLED_CHAIN_IDS,
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
  };
}

function getLegacyChainPublicEnvMap(): Record<ChainScopedPublicEnvName, string | undefined> {
  return {
    NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL,
    NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL,
    NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS,
    NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS,
    NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS,
    NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS,
    NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS,
    NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS,
    NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS,
    NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS,
    NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS
  };
}

function getChainScopedPublicEnvMap(chainId: number): ChainScopedPublicEnvValues {
  switch (chainId) {
    case 1:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_1,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_1,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_1,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_1,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_1,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_1,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_1,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_1,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_1,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_1,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_1
      };
    case 10:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_10,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_10,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_10,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_10,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_10,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_10,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_10,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_10,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_10,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_10,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_10
      };
    case 130:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_130,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_130,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_130,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_130,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_130,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_130,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_130,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_130,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_130,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_130,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_130
      };
    case 137:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_137,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_137,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_137,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_137,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_137,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_137,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_137,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_137,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_137,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_137,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_137
      };
    case 143:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_143,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_143,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_143,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_143,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_143,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_143,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_143,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_143,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_143,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_143,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_143
      };
    case 8453:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_8453,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_8453,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_8453,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_8453,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_8453,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_8453,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_8453,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_8453,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_8453,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_8453,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_8453
      };
    case 43114:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_43114,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_43114,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_43114,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_43114,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_43114,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_43114,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_43114,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_43114,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_43114,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_43114,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_43114
      };
    case 57073:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_57073,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_57073,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_57073,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_57073,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_57073,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_57073,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_57073,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_57073,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_57073,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_57073,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_57073
      };
    case 534352:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_534352,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_534352,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_534352,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_534352,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_534352,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_534352,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_534352,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_534352,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_534352,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_534352,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_534352
      };
    case 11155111:
      return {
        NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL_11155111,
        NEXT_PUBLIC_INDEXER_API_URL: process.env.NEXT_PUBLIC_INDEXER_API_URL_11155111,
        NEXT_PUBLIC_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_REGISTRY_ADDRESS_11155111,
        NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_ROYALTY_SPLIT_REGISTRY_ADDRESS_11155111,
        NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_MODERATOR_REGISTRY_ADDRESS_11155111,
        NEXT_PUBLIC_MARKETPLACE_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS_11155111,
        NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS: process.env.NEXT_PUBLIC_MARKETPLACE_V2_ADDRESS_11155111,
        NEXT_PUBLIC_SHARED_721_ADDRESS: process.env.NEXT_PUBLIC_SHARED_721_ADDRESS_11155111,
        NEXT_PUBLIC_SHARED_1155_ADDRESS: process.env.NEXT_PUBLIC_SHARED_1155_ADDRESS_11155111,
        NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS: process.env.NEXT_PUBLIC_SUBNAME_REGISTRAR_ADDRESS_11155111,
        NEXT_PUBLIC_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_FACTORY_ADDRESS_11155111
      };
    default:
      return {};
  }
}

export function getRootPublicEnv(name: RootPublicEnvName): string | undefined {
  return normalizeEnvValue(getRootPublicEnvMap()[name]);
}

export function getLegacyChainPublicEnv(name: ChainScopedPublicEnvName): string | undefined {
  return normalizeEnvValue(getLegacyChainPublicEnvMap()[name]);
}

export function getScopedChainPublicEnv(name: ChainScopedPublicEnvName, chainId: number): string | undefined {
  return normalizeEnvValue(getChainScopedPublicEnvMap(chainId)[name]);
}
