// @vitest-environment jsdom
import React from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import CreatorSetupClient from './CreatorSetupClient';
vi.mock('wagmi',()=>({useAccount:()=>({address:'0x1111111111111111111111111111111111111111'}),useWalletClient:()=>({data:{signMessage:vi.fn()}})}));
vi.mock('../../lib/profileViewApi',()=>({fetchProfileView:vi.fn().mockResolvedValue({resolution:{profiles:[]},holdings:[]})}));
vi.mock('../../lib/walletSession',()=>({ensureWalletSession:vi.fn().mockResolvedValue(undefined)}));
vi.mock('../HeaderWalletButton',()=>({default:()=>null}));
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();});
it('saves a signed wallet creator page even when local storage is unavailable',async()=>{vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('storage disabled');});vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({profile:{}})}));render(<CreatorSetupClient/>);fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Artist'}});await waitFor(()=>expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText('Save creator page'));await screen.findByText('Your creator page is ready to share.');expect(fetch).toHaveBeenCalledWith('/api/indexer/api/profiles/link',expect.objectContaining({body:expect.stringContaining('"source":"wallet"')}));expect(screen.getByText('View your page').getAttribute('href')).toContain('0x1111');});
it('retains the form and explains a failed setup request',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,json:async()=>({error:'Service unavailable'})}));render(<CreatorSetupClient/>);fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Artist'}});await waitFor(()=>expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText('Save creator page'));await screen.findByText('Service unavailable');expect((screen.getByLabelText('Display name') as HTMLInputElement).value).toBe('Artist');});
it('previews about and safe links without publishing or rendering unsafe links',async()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);render(<CreatorSetupClient/>);fireEvent.change(screen.getByLabelText('About you'),{target:{value:'Independent printmaker'}});fireEvent.change(screen.getByLabelText('Links (one per line)'),{target:{value:'https://example.org/artist\njavascript:alert(1)'}});fireEvent.click(screen.getByText('Preview page'));expect(screen.getByText('Independent printmaker',{selector:'p'})).toBeTruthy();expect(screen.getByRole('link',{name:/Website.*example.org/}).getAttribute('href')).toBe('https://example.org/artist');expect(document.querySelector('a[href^="javascript:"]')).toBeNull();expect(fetchMock).not.toHaveBeenCalled();});
it('publishes editor retro customization in the authenticated profile payload',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({profile:{}})}));render(<CreatorSetupClient/>);fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'My room'}});fireEvent.click(screen.getByRole('button',{name:'Start with a retro room'}));fireEvent.change(screen.getByLabelText('Sticker text'),{target:{value:'STAY WEIRD'}});fireEvent.change(screen.getByLabelText('Top 8 interests (one per line)'),{target:{value:'Art\nMusic'}});await waitFor(()=>expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText('Save creator page'));await screen.findByText('Your creator page is ready to share.');const payload=JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string);expect(payload.design).toMatchObject({theme:'retro',sticker:'STAY WEIRD',top8:['Art','Music']});});
it('blocks publication after failed profile loading, and retry preserves edits',async()=>{const {fetchProfileView}=await import('../../lib/profileViewApi');vi.mocked(fetchProfileView).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({resolution:{profiles:[]},holdings:[]} as never);render(<CreatorSetupClient/>);await screen.findByText('Saved profile could not be loaded. Retry before replacing an existing page.');fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Keep my draft'}});expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByText('Retry profile loading'));await waitFor(()=>expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(false));expect((screen.getByLabelText('Display name') as HTMLInputElement).value).toBe('Keep my draft');});
it('saves custom HTML and CSS through the normal signed profile flow',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({profile:{}})}));render(<CreatorSetupClient/>);fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Code artist'}});fireEvent.click(screen.getByText('Advanced: edit HTML & CSS'));fireEvent.click(screen.getByText('Insert starter HTML & CSS'));fireEvent.change(screen.getByRole('textbox',{name:'Custom HTML',exact:true}),{target:{value:'<h1 class="hello">Hello</h1>'}});fireEvent.change(screen.getByLabelText('Custom CSS'),{target:{value:'.hello{color:pink}'}});await waitFor(()=>expect((screen.getByText('Save creator page') as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText('Save creator page'));await screen.findByText('Your creator page is ready to share.');const body=JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string);expect(body.design.customHtml).toContain('Hello');expect(body.design.customCss).toBe('.hello{color:pink}');expect(body.design.modules).toContain('custom');expect(document.querySelector('iframe')?.getAttribute('sandbox')).toBe('');});

it('restores unsaved profile edits after returning from artwork import without publishing',async()=>{
 const request=vi.fn();vi.stubGlobal('fetch',request);
 const first=render(<CreatorSetupClient/>);
 fireEvent.change(screen.getByLabelText('Display name'),{target:{value:'Pending studio'}});
 fireEvent.change(screen.getByLabelText('About your work'),{target:{value:'Work in progress'}});
 first.unmount();render(<CreatorSetupClient/>);
 await screen.findByText('Unpublished draft restored on this browser.');
 expect((screen.getByLabelText('Display name') as HTMLInputElement).value).toBe('Pending studio');
 expect((screen.getByLabelText('About your work') as HTMLTextAreaElement).value).toBe('Work in progress');
 expect(request).not.toHaveBeenCalled();
});
