'use client';
import s from './ProfileEditorFields.module.css';
import {useState} from 'react';
import {useNftMetadataPreview} from '../../lib/nftMetadata';
import Link from 'next/link';
import ArtworkImage from './ArtworkImage';
import type {ApiMintFeedItem} from '../../lib/indexerApi';
export const artworkKey=(item:ApiMintFeedItem)=>`${item.collection.chainId}:${item.collection.contractAddress.toLowerCase()}:${item.tokenId}`;
function PickerImage({item}:{item:ApiMintFeedItem}){const metadata=useNftMetadataPreview({metadataUri:item.metadataUrl||item.metadataCid,mediaUri:item.mediaUrl,gateway:(process.env.NEXT_PUBLIC_IPFS_GATEWAY||'https://ipfs.io')+'/ipfs'});return <ArtworkImage source={item.mediaUrl||metadata.imageUrl||(item.mediaCid?`ipfs://${item.mediaCid}`:'')} alt={item.draftName||metadata.name||`Artwork ${item.tokenId}`}/>;}
export default function ProfileFeaturedPicker({items,selected,onChange,onRefresh,loading,error}:{items:ApiMintFeedItem[];selected:string[];onChange:(ids:string[])=>void;onRefresh:()=>void;loading:boolean;error:string}){
 const [search,setSearch]=useState('');const all=[...new Map(items.map(item=>[artworkKey(item),item])).values()];
 return <section className={s.section}><h2>Featured artwork</h2><p>Choose up to six pieces and arrange the order they appear on your page.</p><div className={s.artworkToolbar}><label>Find artwork<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, token or collection"/></label><button type="button" className="secondary" disabled={loading} onClick={onRefresh}>{loading?'Loading artwork…':'Refresh artwork'}</button><Link className={`secondary ctaLink ${s.importLink}`} href="/profile/import">Import artwork</Link></div>{error&&<p role="alert">{error}</p>}<p className={s.count} role="status">{selected.length} of 6 selected · {all.length} available</p><ol className={s.selectedList}>{selected.map((key,index)=><li key={key}><span>{all.find(item=>artworkKey(item)===key)?.draftName||`Saved artwork ${key}`}</span><button type="button" className="secondary" disabled={index===0} onClick={()=>{const next=[...selected];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next);}}>Move up</button><button type="button" className="secondary" onClick={()=>onChange(selected.filter(id=>id!==key))}>Remove</button></li>)}</ol><div className="profileArtworkPicker">{all.filter(item=>`${item.draftName||''} ${item.tokenId} ${item.collection.ensSubname||''} ${item.collection.contractAddress}`.toLowerCase().includes(search.toLowerCase())).map(item=>{const key=artworkKey(item);const checked=selected.includes(key);return <label className="card" key={key}><PickerImage item={item}/><span><input type="checkbox" checked={checked} disabled={!checked&&selected.length>=6} onChange={()=>onChange(checked?selected.filter(id=>id!==key):[...selected,key])}/>{item.draftName||`Artwork #${item.tokenId}`}</span><small>{item.collection.ensSubname||item.collection.contractAddress} · Chain {item.collection.chainId}</small></label>;})}</div>{!loading&&!all.length&&<p>No artwork loaded yet. Import a collection or create a piece, then refresh.</p>}</section>;
}
