'use client';
import s from './ProfileEditorFields.module.css';
import {useState} from 'react';
import {safeProfileLink,safeProfileTarget,type ProfileDesign} from '../../../../packages/profile/design.mjs';
export function SocialLinksEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const [platform,setPlatform]=useState('Instagram');const [url,setUrl]=useState('');const [error,setError]=useState('');
 return <section className={s.section}><h2>Social links</h2><p>Add complete public profile URLs. These appear in the Elsewhere section.</p><div className={s.socialForm}><label>Platform<select value={platform} onChange={e=>setPlatform(e.target.value)}>{['Instagram','X','Farcaster','Bluesky','YouTube','TikTok','Discord','Website'].map(p=><option key={p}>{p}</option>)}</select></label><label>{platform} URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…" maxLength={2048}/></label><button type="button" className="secondary" onClick={()=>{const link=safeProfileLink(url);if(!link){setError('Enter a complete http or https link.');return;}const links=[...new Set([...value.split('\n').filter(Boolean),link])];if(links.length>16){setError('Add up to 16 links.');return;}onChange(links.join('\n'));setUrl('');setError('');}}>Add social link</button></div>{error&&<p role="alert">{error}</p>}<ul className={s.linkList}>{value.split('\n').filter(Boolean).map((link,index)=><li key={`${index}:${link}`} className={s.linkRow}><span>{link}</span><button type="button" className="secondary" aria-label={`Remove social link ${index+1}`} onClick={()=>onChange(value.split('\n').filter((_,i)=>i!==index).join('\n'))}>Remove</button></li>)}</ul><details className={s.details}><summary>Edit all links</summary><label>Links (one per line)<textarea value={value} maxLength={4000} onChange={e=>onChange(e.target.value)}/></label></details></section>;
}
export function TopEightEditor({design,onChange}:{design:ProfileDesign;onChange:(design:ProfileDesign)=>void}){
 return <section className={s.section}><h2>Top 8</h2><p>Spotlight other creator profiles or collections. Paste their NFTFactory page link.</p><p>{design.modules.includes('top8')?'Top 8 is visible when you save your page.':'Top 8 is currently hidden on your public page.'}</p>{!design.modules.includes('top8')&&<button type="button" className="secondary" onClick={()=>onChange({...design,modules:[...design.modules,'top8']})}>Show Top 8 on my page</button>}{design.top8Targets.map((target,index)=><fieldset className={s.target} key={index}><legend>Spot {index+1}</legend><label>Display label<input value={target.label} maxLength={60} onChange={e=>onChange({...design,top8Targets:design.top8Targets.map((v,i)=>i===index?{...v,label:e.target.value}:v)})}/></label><label>Profile or collection link<input value={target.url} placeholder="https://nftfactory.org/profile/eth.artist" maxLength={400} onChange={e=>onChange({...design,top8Targets:design.top8Targets.map((v,i)=>i===index?{...v,url:e.target.value}:v)})}/></label>{target.url&&!safeProfileTarget(target.url)&&<p className="error">Use an NFTFactory /profile/… or /collections/network/contract link.</p>}<div className="row"><button type="button" className="secondary" disabled={!index} onClick={()=>{const next=[...design.top8Targets];[next[index-1],next[index]]=[next[index],next[index-1]];onChange({...design,top8Targets:next});}}>Move up</button><button type="button" className="secondary" onClick={()=>onChange({...design,top8Targets:design.top8Targets.filter((_,i)=>i!==index)})}>Remove</button></div></fieldset>)}<button type="button" className="secondary" disabled={design.top8Targets.length>=8} onClick={()=>onChange({...design,top8Targets:[...design.top8Targets,{label:'',url:''}],modules:design.modules.includes('top8')?design.modules:[...design.modules,'top8']})}>Add profile or collection</button></section>;
}
