'use client';
import {useState} from 'react';
import {type ProfileDesign} from '../../../../packages/profile/design.mjs';
import {applyProfileTemplate,profileTemplates} from '../../lib/profileTemplates';
import {pageStarterHtml,pageStarterCss} from '../../lib/profilePageDocument';
import {starterCss,starterHtml} from '../../lib/profileCustomCode';
import s from './ProfileDesignEditor.module.css';
export default function ProfileDesignEditor({design,onChange}:{design:ProfileDesign;onChange:(design:ProfileDesign)=>void}){
 const [previous,setPrevious]=useState<ProfileDesign|null>(null);
 return <section><h3>Starting templates</h3><p>Pick a layout and palette. Your words, images, featured artwork, and custom code are kept.</p><div className={s.templates}>{profileTemplates.map(t=><button className={s.template} type="button" key={t.id} aria-label={t.id==='retro'?'Start with a retro room':undefined} onClick={()=>{setPrevious(design);onChange(applyProfileTemplate(design,t.id));}}><span className={`${s.swatch} ${s[t.id]}`} aria-hidden="true"><i/><i/><i/></span><strong>{t.name}</strong><span>{t.description}</span></button>)}</div>{previous&&<button type="button" className="secondary" onClick={()=>{onChange(previous);setPrevious(null);}}>Undo template change</button>}
 <details className={s.advanced}><summary>Advanced: edit HTML & CSS</summary><p>Choose a custom section or design the whole profile. Whole-page mode replaces the template, including its header and layout. Wallet controls stay outside your design. Scripts, forms and embedded apps are disabled.</p>
 <label>Code applies to<select value={design.customScope} onChange={e=>onChange({...design,customScope:e.target.value as 'page'|'section',customHeight:e.target.value==='page'?1200:design.customHeight})}><option value="section">One custom section</option><option value="page">Entire profile page</option></select></label>{design.customScope==='page'&&<p className="hint">Use {'{{intro}}, {{featured}}, {{artwork}}, {{about}}, {{links}}, {{collections}}, {{top8}} and {{panels}}'} to include your live profile content. CSS can style every element inside the page.</p>}<label className="studioCheckbox"><input type="checkbox" checked={design.modules.includes('custom')} onChange={e=>onChange({...design,modules:e.target.checked?[...design.modules,'custom']:design.modules.filter(m=>m!=='custom')})}/>Show custom HTML section</label>
 <label>Custom HTML<textarea className={s.code} spellCheck={false} rows={12} maxLength={20000} value={design.customHtml} onChange={e=>onChange({...design,customHtml:e.target.value})}/></label><p className="hint">{design.customHtml.length}/20,000 characters · semantic HTML and class/id attributes supported</p>
 <label>Custom CSS<textarea className={s.code} spellCheck={false} rows={12} maxLength={20000} value={design.customCss} onChange={e=>onChange({...design,customCss:e.target.value})}/></label><p className="hint">{design.customCss.length}/20,000 characters</p>
 {design.customScope==='page'&&<button type="button" className="secondary" onClick={()=>{setPrevious(design);onChange({...design,customHtml:pageStarterHtml,customCss:pageStarterCss});}}>Load whole-page layout</button>}<label>Custom canvas height<select value={design.customHeight} onChange={e=>onChange({...design,customHeight:Number(e.target.value)})}><option value={320}>Compact · 320 px</option><option value={560}>Standard · 560 px</option><option value={800}>Tall · 800 px</option><option value={1200}>Full canvas · 1200 px</option></select></label>
 <button type="button" className="secondary" disabled={Boolean(design.customHtml||design.customCss)} onClick={()=>onChange({...design,customHtml:design.customScope==='page'?pageStarterHtml:starterHtml,customCss:design.customScope==='page'?pageStarterCss:starterCss,modules:design.modules.includes('custom')?design.modules:[...design.modules,'custom']})}>Insert starter HTML & CSS</button><p className="hint">The starter is available when both code fields are empty. Preview below, then save a draft or publish through your wallet.</p></details></section>;
}
