'use client';
import ProductPageHeader from '../ProductPageHeader';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {createPublicClient,http,formatEther,parseAbi,type Address} from 'viem';
import {useAccount,useSwitchChain,useWalletClient} from 'wagmi';
import {fetchActiveListings,type ApiActiveListingItem} from '../../lib/indexerApi';
import {getAppChain,getEnabledAppChains,getPrimaryAppChainId} from '../../lib/chains';
import {getContractsConfig} from '../../lib/contracts';
import {marketplaceAbi,ZERO_ADDRESS} from '../../lib/marketplace';
import {nftPath} from '../../lib/assetRoutes';
import {assertPurchasableListing,listingMatchesDeployment} from '../../lib/marketplacePurchase';
import ArtworkImage from '../profile/ArtworkImage';
const buyAbi=parseAbi(['function buy(uint256 listingId) payable']);
export default function MarketplaceClient(){
 const {address,chainId:walletChain}=useAccount();const {data:wallet}=useWalletClient();const {switchChainAsync}=useSwitchChain();
 const [chainId,setChainId]=useState(getPrimaryAppChainId);const [items,setItems]=useState<ApiActiveListingItem[]>([]);const [cursor,setCursor]=useState(0);const [next,setNext]=useState<number|null>(null);const [attempt,setAttempt]=useState(0);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<ApiActiveListingItem|null>(null);const [hash,setHash]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');void fetchActiveListings(cursor,24,undefined,{chainId}).then(data=>{if(!active)return;setItems(current=>cursor===0?data.items:[...current,...data.items.filter(item=>!current.some(c=>c.listingId===item.listingId))]);setNext(data.canLoadMore?data.nextCursor:null);}).catch(()=>{if(active)setError('Listings are temporarily unavailable. Please retry.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[chainId,cursor,attempt]);
 async function buy(){
   if(!selected||!address||!wallet||busy)return;setBusy(true);setError('');setHash('');
   try{
     if(walletChain!==chainId){await switchChainAsync({chainId});throw new Error('Network switched. Review the price and press Confirm purchase again.');}
     const config=getContractsConfig(chainId);const client=createPublicClient({chain:getAppChain(chainId),transport:http(config.rpcUrl,{timeout:10000,retryCount:0})});
     if(!listingMatchesDeployment(selected,chainId,config.marketplace))throw new Error('This listing belongs to another marketplace deployment. Refresh before continuing.');
     const id=BigInt(selected.listingId);const listing=await client.readContract({address:config.marketplace,abi:marketplaceAbi,functionName:'listings',args:[id]});
     assertPurchasableListing(selected,listing,Math.floor(Date.now()/1000));
     if(listing[0].toLowerCase()===address.toLowerCase())throw new Error('You already own this listing. Manage it in your studio.');
     const simulation=await client.simulateContract({account:address as Address,address:config.marketplace,abi:buyAbi,functionName:'buy',args:[id],value:listing[6]});
     if(await wallet.getChainId()!==chainId||wallet.account.address.toLowerCase()!==address.toLowerCase())throw new Error('Wallet changed. Reconnect and retry.');
     const tx=await wallet.writeContract(simulation.request);setHash(tx);const receipt=await client.waitForTransactionReceipt({hash:tx,timeout:120000});if(receipt.status!=='success')throw new Error('The purchase reverted. No NFT was purchased.');setSelected(null);setItems(current=>current.filter(item=>item!==selected));setError('Purchase confirmed. Ownership will update after indexing.');
   }catch(error){setError(error instanceof Error?error.message:'Purchase was not completed.');}finally{setBusy(false);}
 }
 const visible=items.filter(item=>listingMatchesDeployment(item,chainId,getContractsConfig(chainId).marketplace)&&item.active&&item.paymentToken.toLowerCase()===ZERO_ADDRESS&&BigInt(item.expiresAtRaw)>BigInt(Math.floor(Date.now()/1000))&&`${item.token?.draftName||''} ${item.collectionAddress} ${item.tokenId}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="studioPage"><ProductPageHeader section="Collect artwork" title="Marketplace" description="Browse fixed-price NFTs. Review the artwork, network, and price before you buy." actions={<Link className="ctaLink secondary" href="/profile/listings">Manage your listings</Link>} /><div className="marketplaceFilters"><label>Network<select value={chainId} disabled={busy} onChange={e=>{setChainId(Number(e.target.value));setCursor(0);setItems([]);setSelected(null);}}>{getEnabledAppChains().map(chain=><option key={chain.id} value={chain.id}>{chain.name}</option>)}</select></label><label>Search loaded listings<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Artwork, contract, or token ID"/></label></div>{error&&<p role="status">{error}</p>}{hash&&<p className="receiptHash">Transaction: {hash}</p>}{loading&&<p role="status">Loading listings…</p>}<button className="secondary" disabled={busy||loading} onClick={()=>{setCursor(0);setAttempt(v=>v+1);}}>Refresh listings</button>{!loading&&!visible.length&&<p>No matching listings yet. Try another search or return as creators add work.</p>}<div className="creatorArtworkGrid">{visible.map(item=><article className="card artworkCard" key={`${chainId}:${item.listingId}`}><Link className="artworkCardImage" href={nftPath(chainId,item.collectionAddress,item.tokenId)}><ArtworkImage source={item.token?.mediaUrl||''} alt={item.token?.draftName||`Artwork #${item.tokenId}`}/></Link><div className="artworkCardBody"><p className="eyebrow">{getAppChain(chainId).name}</p><h2>{item.token?.draftName||`Artwork #${item.tokenId}`}</h2><p>{formatEther(BigInt(item.priceRaw))} ETH · {item.amountRaw} item(s)</p><button disabled={busy} onClick={()=>{setSelected(item);setError('');}}>Review purchase</button></div></article>)}</div>{next!==null&&<button disabled={loading||busy} onClick={()=>setCursor(next)}>Load more listings</button>}{selected&&<section className="card formCard purchaseReview" aria-labelledby="purchase-title"><h2 id="purchase-title">Review your purchase</h2><p>Artwork #{selected.tokenId} on {getAppChain(chainId).name}</p><p className="receiptHash">Contract: {selected.collectionAddress}</p><p className="receiptHash">Seller: {selected.sellerAddress}</p><p>Total: <strong>{formatEther(BigInt(selected.priceRaw))} ETH</strong>, plus the network fee shown by your wallet.</p><p className="hint">The protocol fee is deducted from seller proceeds. This marketplace does not enforce separate creator royalties. We recheck and simulate the purchase before asking your wallet to approve.</p><div className="row"><button disabled={!address||!wallet||busy} onClick={()=>void buy()}>{busy?'Waiting for confirmation…':walletChain!==chainId?'Switch network':'Confirm purchase'}</button><button className="secondary" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button></div>{!address&&<p>Connect your wallet using the button at the top to continue.</p>}</section>}</section>;
}
